# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2cf7a5d15b5baf85901d26bd251d5e689d752cafdc8f63ae705910349ccc9b620b0993aaaca7eeaceb9fcf79db7687c7e2aad45c5ce5995d793988394ff386d

test:
  secret_key_base: 929ab7f90fa8666acfd76dee86205e4ec11fd03415200e2ec129b5230f59332e828b16fa83ffd04bea8f7e2ad816f6f9d0abffd2d70f9b9e724271e06ea754a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
